### ISSUE TITLE
libetpan17 failed to build on Mac OS X 10.13

### ISSUE THREAD

**Issue by x-ii-ii-x** [fink/fink-distributions#464]
Hi-Ha! Howdy,

Just got this error while trying to install claws-mail from source.
libetpan17 failed to build with a SSL? related error.
Not in a hurry, if @nieder or anyone has an idea about that, I would be glad to assist.

Package manager version: 0.45.0
Distribution version: selfupdate-rsync Thu Sep 19 15:58:42 2019, 10.13, x86_64
Trees: local/main stable/main
Xcode.app: 10.1
Xcode command-line tools: 10.1.0.0.1.1539992718
Max. Fink build jobs:  1

```
/../src/data-types -I../../../src/low-level/imf -I/sw/include/db6 -I/sw/include -D_REENTRANT -I/sw/include -g -O2 -W -Wall -MT newsfeed_item.lo -MD -MP -MF .deps/newsfeed_item.Tpo -c newsfeed_item.c  -fno-common -DPIC -o .libs/newsfeed_item.o
mv -f .deps/newsfeed_item.Tpo .deps/newsfeed_item.Plo
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../..  -I../../../include -I../../../src/data-types -I../../../src/low-level/imf -I/sw/include/db6 -I/sw/include -D_REENTRANT -I/sw/include  -g -O2 -W -Wall -MT newsfeed.lo -MD -MP -MF .deps/newsfeed.Tpo -c -o newsfeed.lo newsfeed.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../.. -I../../../include -I../../../src/data-types -I../../../src/low-level/imf -I/sw/include/db6 -I/sw/include -D_REENTRANT -I/sw/include -g -O2 -W -Wall -MT newsfeed.lo -MD -MP -MF .deps/newsfeed.Tpo -c newsfeed.c  -fno-common -DPIC -o .libs/newsfeed.o
newsfeed.c:538:8: error: duplicate case value 'CURLE_PEER_FAILED_VERIFICATION'
  case CURLE_SSL_CACERT:
       ^
/sw/include/curl/curl.h:624:26: note: expanded from macro 'CURLE_SSL_CACERT'
#define CURLE_SSL_CACERT CURLE_PEER_FAILED_VERIFICATION
                         ^
newsfeed.c:533:8: note: previous case defined here
  case CURLE_SSL_PEER_CERTIFICATE:
       ^
/sw/include/curl/curl.h:631:36: note: expanded from macro
      'CURLE_SSL_PEER_CERTIFICATE'
#define CURLE_SSL_PEER_CERTIFICATE CURLE_PEER_FAILED_VERIFICATION
                                   ^
1 error generated.
make[7]: *** [newsfeed.lo] Error 1
make[7]: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7/src/low-level/feed'
make[6]: *** [all] Error 2
make[6]: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7/src/low-level/feed'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7/src/low-level'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7/src/low-level'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7'
make: *** [all] Error 2
make: Leaving directory `/sw/src/fink.build/libetpan17-shlibs-1.7-1/libetpan-1.7'
### execution of /usr/bin/make failed, exit code 2
### execution of /tmp/fink.v7tJ8 failed, exit code 2
Removing runtime build-lock...
Removing build-lock package...
/sw/bin/dpkg-lockwait -r fink-buildlock-libetpan17-shlibs-1.7-1
(Reading database ... 218287 files and directories currently installed.)
Removing fink-buildlock-libetpan17-shlibs-1.7-1 ...
Failed: phase compiling: libetpan17-shlibs-1.7-1 failed
```

**Comment by nieder** [comment]
Fixed by 93e6b73
