### ISSUE TITLE
root5 FTBFS: tangled c++ standards and deps

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#886]
While working through migrating some packages with old dependencies, I was working on root5, currently 5.34.38-2, on OS X 10.13. First, there's a simple missing dependency on lz4-dev/lz4-shlibs dependencies. But there is also a compiler failure:
```
clang++ -O2 -m64 -pipe -Wshadow -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -Iinclude -DR__HAVE_CONFIG   -stdlib=libc++   -pthread -I/sw/include/xrootd -Wno-unused-parameter -Wno-shadow -o net/netxng/src/TNetXNGFileStager.o -c /sw/build.build/root5-5.34.38-3/root/net/netxng/src/TNetXNGFileStager.cxx
In file included from /sw/build.build/root5-5.34.38-3/root/net/netxng/src/TNetXNGFileStager.cxx:22:
In file included from include/TNetXNGSystem.h:31:
In file included from /sw/include/xrootd/XrdCl/XrdClXRootDResponses.hh:22:
/sw/include/xrootd/XrdCl/XrdClBuffer.hh:50:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      Buffer( Buffer &&buffer )
                     ^
[several warnings like that]
/sw/include/xrootd/XrdCl/XrdClBuffer.hh:52:16: error: rvalue reference to type 'XrdCl::Buffer' cannot bind to lvalue of type 'XrdCl::Buffer'
        Steal( std::move( buffer ) );
               ^~~~~~~~~~~~~~~~~~~
[several errors like that]
```
The build system has an option to enable c++11, so I added `--enable-cxx11`. But then I fail even earlier:
```
clang++ -O2 -m64 -pipe -Wshadow -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -Iinclude -DR__HAVE_CONFIG   -std=c++11 -stdlib=libc++   -pthread -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17 -Iinclude/cint -o bindings/ruby/src/drr.o -c /sw/build.build/root5-5.34.38-3/root/bindings/ruby/src/drr.cxx
[some c++17 deprecation warnings]
In file included from /sw/build.build/root5-5.34.38-3/root/bindings/ruby/src/drr.cxx:26:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h:368:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_ARCH "universal-"RUBY_PLATFORM_OS
                              ^
```
The simplest fix is probably just to use fink's ruby, since we control it and can fix it if needed. If I adjust that compiler call to use our ruby2.6, the error goes away. But the autoconf is a mess for ruby, with variables that seem to overwrite each other, and autodetection that ignores its own documentation about what variables to use to set things.

I think I'm out here. There is a newer upstream (now major-version 6), so maybe we should just jump to (hopefully clean) "root6" package?
