### PR TITLE
Fix exuberant-ctags build on 10.14 with __unused macro issues.

### LINKED ISSUE #573: exuberant-ctags fails to build on 10.14+ (__unused macro confusion)
This is the error:
```
    In file included from main.c:62:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/dirent.h:80:2: error: use of undeclared identifier 'unused'
            __unused long   __padding; /* (__dd_rewind space left for bincompat) */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:161:40: note: expanded from macro '__unused'
    #define __unused        __attribute__((__unused__))
                                           ^
    ./general.h:60:37: note: expanded from macro '__unused__'
    # define __unused__  __attribute__((unused))
                                        ^
    1 error generated.
    make: *** [main.o] Error 1
```
Homebrew and MacPorts have different fixes. Homebrew just unsupports the conflicting macro (homebrew/homebrew-core#42147). MacPorts renames the macro to [its own internal namespace](https://github.com/macports/macports-ports/blob/master/devel/ctags/files/unused_namespace.patch)  .

### PR DESCRIPTION
**Pull request by nieder**
Based of MP fix.
Closes #573.

### CODE REVIEW

**Comment by nieder** [comment]
Pushing. It's been a month and is a FTBFS.
