### ISSUE TITLE
brotli-py needs versioned dep on libbrotli

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#261]
brotli-py27-1.0.5-1 builds ok with libbrotli1-shlibs-1.0.5 (even if the dev is not installed). If I have libbrotli1-shlibs-1.0.3 installed, I get this failure:
````
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -I/sw/include -DOS_MACOSX=1 -Ic/include -I/sw/include/python2.7 -c c/dec/bit_reader.c -o bin/temp.macosx-10.11-x86_64-2.7/c/dec/bit_reader.o
In file included from c/dec/bit_reader.c:9:
In file included from c/dec/./bit_reader.h:14:
c/dec/../common/platform.h:72:28: error: token is not a valid binary operator in a preprocessor subexpression
#if BROTLI_GNUC_HAS_BUILTIN(__builtin_expect, 3, 0, 0) || \
    ~~~~~~~~~~~~~~~~~~~~~~~^
c/dec/../common/platform.h:118:30: error: token is not a valid binary operator in a preprocessor subexpression
#if BROTLI_GNUC_HAS_ATTRIBUTE(always_inline, 4, 0, 0) ||                       \
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
c/dec/../common/platform.h:126:32: error: token is not a valid binary operator in a preprocessor subexpression
#elif BROTLI_MSVC_VERSION_CHECK(12, 0, 0)
      ~~~~~~~~~~~~~~~~~~~~~~~~~^
c/dec/../common/platform.h:128:30: error: token is not a valid binary operator in a preprocessor subexpression
#elif BROTLI_TI_VERSION_CHECK(7, 0, 0) && defined(__cplusplus)
      ~~~~~~~~~~~~~~~~~~~~~~~^
````

**Comment by danielj7** [comment]
Funny thing is that it doesn't actually use libbrotli, it builds its own static version but because -I/sw/include always comes first, it will find installed headers if present. I can't find a way to change the order of flags so I added a BDep on libbrotli1.
