### ISSUE TITLE
encfs fails to build against openssl110

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#765]
encfs fails to build, trying to use removed versions of the OpenSSL API:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -MD -I/sw/include -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D__STDC_FORMAT_MACROS -I/sw/include/osxfuse -DRLOG_COMPONENT=encfs -I/sw/include -I/sw/include -I/sw/opt/boost-1_58//include -I../intl -DLOCALEDIR=\"/sw/share/locale\" -W -Wall -Wpointer-arith -Wwrite-strings -MD -D_THREAD_SAFE -pthread -std=gnu++11 -MT SSL_Cipher.lo -MD -MP -MF .deps/SSL_Cipher.Tpo -c SSL_Cipher.cpp  -fno-common -DPIC -o .libs/SSL_Cipher.o
SSL_Cipher.cpp:82:14: error: variable has incomplete type 'EVP_MD_CTX' (aka 'evp_md_ctx_st')
  EVP_MD_CTX cx;
             ^
/sw/include/openssl/ossl_typ.h:92:16: note: forward declaration of 'evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
SSL_Cipher.cpp:236:18: error: field has incomplete type 'EVP_CIPHER_CTX' (aka 'evp_cipher_ctx_st')
  EVP_CIPHER_CTX block_enc;
                 ^
/sw/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
               ^
...
```
This is with openssl110-dev installed. encfs is also missing a dependency on openssl110-{dev,shlibs}.

**Comment by mringwal** [comment]
Hi. Thanks for reporting. I'm sorry, I din't have fink running since upgrading to 10.15. Please either drop the package, limit it to older versions, or do whatever causes the least work for you. I'm not able to maintain any of my fink packages anymore. Best regards, Matthias.

**Comment by dmacks** [comment]
Upstream appears to have supported openssl110 since v1.9.2 (most recent release is 1.9.5) See https://github.com/vgough/encfs for current development.

**Comment by nieder** [comment]
@mringwal Thank you for your past time and help with your Fink packages. Good luck.
