### ISSUE TITLE
libusb-0.1.12 FTBFS on macOS12 (deprecated IOMasterPort)

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#863]
The older libusb-0.1.12 fails to build on macOS 12.1 with this error:
```
 gcc -DHAVE_CONFIG_H -I. -I/opt/sw/include -Werror -no-cpp-precomp -g -O2 -g -Wall -MT darwin.lo -MD -MP -MF .deps/darwin.Tpo -c darwin.c  -fno-common -DPIC -o .libs/darwin.o
darwin.c:1171:5: error: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Werror,-Wdeprecated-declarations]
    IOMasterPort(masterPort, &masterPort);
    ^~~~~~~~~~~~
    IOMainPort
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
IOMasterPort( mach_port_t       bootstrapPort,
^
1 error generated.
make[2]: *** [darwin.lo] Error 1
```
This old libN is long abandoned. It's used by the following packages:
- [ ] gnupg-unified (@nieder)
- [ ] xpwn (none)
- [ ] openocd (none)
- [ ] avrdude (@mringwal)
- [ ] mspdebug (none)
- [ ] libftdi (none)
- [ ] libgphoto2.6 (@nieder)
- [ ] ztex (none)
- [ ] nut (@clepple )
- [ ] gnokii7 (Ben Reed)
- [ ] gpsbabel (@clepple )
- [ ] sispmctl (none)

**Comment by dmacks** [comment]
This FTBFS can surely be resolved by removing `-Werror`, but we should also work on migrating as much as possible off an old libversion.

**Comment by dmacks** [comment]
I'm tagging "OLD_USB" for ones that cannot easily be migrated.

**Comment by clepple** [comment]
Theoretically, we're close to [upgrading NUT to libusb-1.0](https://github.com/networkupstools/nut/issues/300), but TBH userspace access to USB devices on macOS seems to keep breaking at runtime in ways that aren't easy to debug or fix (despite libusb-0.1 having worked just fine on other platforms for years after it was abandoned upstream).

**Comment by dmacks** [comment]
ztex's recent upstream versions use newer libusb, but they distribute only a prebuilt libusb4java.dylib that apparently embeds its own copy of it rather than a source that compiles and links against it.

**Comment by dmacks** [comment]
gnokii is dead upstream and debian's packaging of it still uses old libusb.

**Comment by dmacks** [comment]
@mringwal there's a new avrdude upstream that has a `--disable-libusb_1_0` flag (https://github.com/avrdudes/avrdude/commit/9cb9f504ae886003be6fe2d24249479a444b23d5). Not sure why it would ever actually want to use older *and* newer, rather than just one or the other anyway.

**Comment by mringwal** [comment]
@dmacks Thanks for looking into this. If avrdude compiels with libusb-1.0, please update it. If not, no idea what to do.
I'm not using Fink anymore. Could you remove me from the maintainer field please?
Thanks again!

**Comment by jimklimov** [comment]
Just in case, is it an option to use libusb-compat for those projects on MacOS? https://github.com/libusb/libusb-compat-0.1

This is supposed to be a sort of fork from libusb-1.0 codebase with API for 0.1 replacement, with some caveats reported in their README. I am not sure how much they are otherwise in- or out- of sync with "true" libusb-1.0.

**Comment by nieder** [comment]
@jimklimov thanks for the pointer on libusb-compat-0.1. I've successfully built it on 12.1. Will now try to use it to compile one of our current packages using the old libusb-0.1.
@dmacks it builds the library `libusb-0.1.4.dylib`, so I'll call the packages `libusb-compat-0.1.4-shlibs` and `libusb-compat-0.1.4-dev`

**Comment by nieder** [comment]
libusb-compat successfully worked with gnupg-unified, avrdude, and mspdebug.

**Comment by dmacks** [comment]
> @dmacks I'm not using Fink anymore. Could you remove me from the maintainer field please? Thanks again!

@mringwal Done. Thanks for your many years of maintaining so many packages!

**Comment by dmacks** [comment]
> libusb-compat successfully worked with gnupg-unified, avrdude, and mspdebug.

I pushed avrdude's new version using libusb-compat. Thanks @jimklimov !

**Comment by jimklimov** [comment]
Super, glad to help from the peanut gallery ;)

NUT master branch should be good with libusb-1.0 soon.

**Comment by mringwal** [comment]
> > @dmacks I'm not using Fink anymore. Could you remove me from the maintainer field please? Thanks again!
> 
> @mringwal Done. Thanks for your many years of maintaining so many packages!

@dmacks You're welcome, but I have to thank you and the other old timers for all your work!

**Comment by jimklimov** [comment]
Hi, on behalf of the mentioned NUT project, the master branch now includes the changes for "native" libusb-1.0 support (release-cutting would happen later, though - got some more PRs pending to merge, at least).

**Comment by nieder** [comment]
With db8d3cb8b760454345014d7344ac091a3d5c15e2 for gpsbabel, the old libN of nut (v2.7.4) is the last user of the really old libusb-0.1 package. I can't find anything using the old libupsclient4-shlibs and libnutclient0-shlibs libraries from nut-2.7.4.
