### ISSUE TITLE
libtevent0-0.9.39-1: waf fails with: AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink-distributions#1095]
Pretty much the same build failure as was seen in #1093 with libtalloc2:
```
[ -x /usr/bin/python3 ] && pyversion=3 ; PYTHON=/usr/bin/python$pyversion make -w
make: Entering directory '/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39'
PYTHONHASHSEED=1 WAF_MAKE=1 /usr/bin/python3 `PATH=buildtools/bin:../../buildtools/bin:$PATH which waf` build
Waf: Entering directory `/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/bin/default'
Traceback (most recent call last):
  File "/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/third_party/waf/waflib/Scripting.py", line 158, in waf_entry_point
    run_commands()
  File "/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/third_party/waf/waflib/Scripting.py", line 251, in run_commands
    ctx = run_command(cmd_name)
  File "/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/third_party/waf/waflib/Scripting.py", line 235, in run_command
    ctx.execute()
  File "/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/third_party/waf/waflib/Scripting.py", line 573, in execute
    return execute_method(self)
  File "/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/third_party/waf/waflib/Build.py", line 231, in execute
    self.execute_build()
  File "/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/third_party/waf/waflib/Build.py", line 245, in execute_build
    self.pre_build()
  File "/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39/third_party/waf/waflib/Build.py", line 542, in pre_build
    m(self)
  File "./buildtools/wafsamba/samba_deps.py", line 1106, in check_project_rules
    tstart = time.clock()
AttributeError: module 'time' has no attribute 'clock'
make: *** [Makefile:7: all] Error 2
make: Leaving directory '/opt/sw/src/fink.build/libtevent0-0.9.39-1/tevent-0.9.39'
### execution of [ failed, exit code 2
### execution of /tmp/fink.yJGy4 failed, exit code 2
Removing runtime build-lock...
Removing build-lock package...
/opt/sw/bin/dpkg-lockwait -r fink-buildlock-libtevent0-0.9.39-1
(Reading database ... 
dpkg: serious warning: files list file for package `fink-buildlock-ccp4-6.5-1' missing, assuming package has no files currently installed.
1029184 files and directories currently installed.)
Removing fink-buildlock-libtevent0-0.9.39-1 ...
```
I'm on x86_64 Big Sur with Xcode 13. cc @danielj7
(it looks like @nieder may be planning an update here, as per the notes added in fb98be5, but I thought it would be good to ensure this is tracked anyways...)
