### ISSUE TITLE
Python 3.8 fails build on Mac OS 10.11

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#630]
I know the OS is old, but that is the latest my old personal hardware supports.  I maintain a python package and was updating it from python 2.7 to a more recent version.  Python 3.7 works and builds, but python 3.8 has a problem (same sort of finding header files? as 2.7 on a more recent OS???).
Mac OS 10.11.6 and Xcode & Tools 8.2.1

In this case the error is:
gcc -bundle -undefined dynamic_lookup -L/sw/lib -L/sw/lib -L/sw/lib -I/sw/include build/temp.macosx-10.11-x86_64-3.8/sw/src/fink.bu
ild/python38-3.8.0-1/Python-3.8.0/Modules/readline.o -L/usr/lib/termcap -L. -L/sw/lib -lreadline -lncursesw -o build/lib.macosx-10.
11-x86_64-3.8/readline.cpython-38-darwin.so
ld: warning: directory not found for option '-L/usr/lib/termcap'
/sw/src/fink.build/python38-3.8.0-1/Python-3.8.0/Modules/_cursesmodule.c:621:9: error: implicit declaration of function 'setcchar' 
is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        setcchar(&wcval, wstr, attr, attr_to_color_pair(attr), NULL);
        ^

The setcchar seems to be defined in /sw/include//ncursesw/curses.h and ncurses.h.
% grep -r setcchar  /sw/include/
/sw/include//ncursesw/curses.h:extern NCURSES_EXPORT(int) setcchar (cchar_t *, const wchar_t *, const attr_t, short, const void *)/* implemented */
/sw/include//ncursesw/ncurses.h:extern NCURSES_EXPORT(int) setcchar (cchar_t *, const wchar_t *, const attr_t, short, const void *);	/* implemented */
[python38build.txt](https://github.com/fink/fink-distributions/files/4672710/python38build.txt)

**Comment by dhomeier** [comment]
@sth0 this looks like a duplicate of the build failure #530 on 10.12.
The patch file is inserting a wrong `ncurses` include path; my take on that is that it went unnoticed because on 10.14 and higher `CPPFLAGS` are reset in the `CompileScript`.

This should be fixed in the update to 3.8.3 in #540, please let me know if you encounter any problems building that version on 10.11. Also, did you try if the Python 2.7 revision in the same PR builds for you?

**Comment by sth0** [comment]
Derek, it does look like it, but the solution there doesn't seem to work.  I updated my distribution and rebuilt 3 versions python3.8, 2.7 and 3.7 just now.  I get errors with python3.8 and not with python 2.7 and 3.7.  I believe the fix mentioned in #540 has been pushed to master and thus it should work.  At least looking at the patch file seems to show that python 3.8 has the patch.  I believe all 3 version build correctly on my other system 10.14.6 / Xcode 11.3.1
Mac OS X 10.11.6 and Xcode 8.2.1
[python38build.txt](https://github.com/fink/fink-distributions/files/4703887/python38build.txt)

If it would help, I can upload the logs from the successful builds.

**Comment by nieder** [comment]
That log is still building python38-3.8.0-1. The stuff in #540 builds python38-3.8.3.

**Comment by sth0** [comment]
I agree, as I said, is it just that has not been pushed?  Self-update reports
Your branch is up-to-date with 'origin/master'.
Am I just missing something?  Or is there a hold up for other reasons with the python 3.8.3 update?

**Comment by dhomeier** [comment]
No, you're right. It is not in master because #540 is not merged.

**Comment by sth0** [comment]
Thanks, now I understand where am!  I am learning the intricacies of git as we go.
Thanks for all you do.

**Comment by nieder** [comment]
@sth0 
Can you try to apply the fix to flag-sort that's in #646 ? 
And also confirm the layout of your SDKs as explained here: https://sourceforge.net/p/fink/mailman/message/37031093/

**Comment by dmacks** [comment]
ping @nieder, @sth0 There have been several layers of python build-fixes applied recently. Is this issue-ticket still current?

**Comment by sth0** [comment]
My notes say that I successfully rebuilt python 2.7, 3.7 and 3.8 on OS 10.11 on 8/1.  There have been modifications since then so I will try a rebuild and report back.

**Comment by sth0** [comment]
Finally finished building on MacOS 10.11, all 3 versions build correctly, with the current distribution.  This issue can be closed.
