### ISSUE TITLE
building setuptools-scm-py 3.1.0 deadlocks if older version installed

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#219]
If I have the old setuptools-scm-py-1.15.6 installed, building v3.1.0 deadlocks because of the BuildConflicts line in the new release. This blocks the bindist.

````
dpkg: regarding .../fink-buildlock-setuptools-scm-py27-3.1.0-1_2018.08.10-05.53.56_darwin-x86_64.deb containing fink-buildlock-setuptools-scm-py27-3.1.0-1:
 fink-buildlock-setuptools-scm-py27-3.1.0-1 conflicts with setuptools-scm-py27 (<= 2.0.0)
  setuptools-scm-py27 (version 1.15.6-1) is installed.
````

This was added in 9b2ebdf by @dhomeier. It's not immediately clear why BC: is needed for an old version of self.

**Comment by danielj7** [comment]
I see why he did it; setuptools fails to build the package if the older setuptools-scm-py is installed with the error `ImportError: module 'setuptools_scm.hg' has no attribute 'FILES_COMMAND'`, but the BC obviously won't work either. I'll have to give it some thought. It's really annoying how interconnected all these packages are. They're really not meant to be built separately but as a unit. Not very package manager friendly.
