### PR TITLE
trackballs: Apply upstream patch to build on 10.13

### PR DESCRIPTION
**Pull request by nieder**
@microtherion 
On 10.13, trackballs fails to build with this error:
```
g++ -DLOCALEDIR=\"/sw/share/locale\" -DHAVE_CONFIG_H -I. -I.. -DSHARE_DIR=\"/sw/share/trackballs\" -DPACKAGE=\"trackballs\" -DVERSION=\"1.1.4\"  -I/sw/include -I/opt/X11/include  -g -g -O2 -I/sw/include -I/sw/include -D_THREAD_SAFE  -I./ -I../ -DDEFAULT_RESOLUTION=1 -MT trackballs-glHelp.o -MD -MP -MF .deps/trackballs-glHelp.Tpo -c -o trackballs-glHelp.o `test -f 'glHelp.cc' || echo './'`glHelp.cc
glHelp.cc:132:13: error: 'abs' is missing exception specification 'throw()'
inline Real abs(Real v) {return v>0.0?v:-v;}
```
The original SF trackballs has been discontinued, but an active fork at https://trackballs.github.io/ has the patch needed to fix the error.

### CODE REVIEW

**Comment by microtherion** [comment]
👍 haven't tested the fix, but it looks principled and correct to me.
