### ISSUE TITLE
No telnet beyond 11.0 distro

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1296]
Our telnet.info is Apple's https://github.com/apple-opensource/remote_cmds v60, which doesn't build on my 26.0 (looks like issue #1115), which is a problem because recent OS X stopped supplying telnet. There is a newer release v63 on that apple repo, which is still almost 6 years old, and that I have not yet tried. Anyone know why we are using Apple's rather than GNU's? I tried inetutils-2.7 (what Debian is currently using)...its build-system is a bit of a mess, but it gave me a functional telnet executable.

**Comment by TheSin-** [comment]
Use deb helper to build detain packages, grep my exp for deb helper and see how it works. it'll used the debian build methods and you don't have to fuss with it.

**Comment by nieder** [comment]
That v63 telnet in Apple's opensource is actually telnet_d_.

I've patched some things in telnet.info and it goes past the xcodebuild stage into actually compiling, but running into a declaration failure:
```C
nieder $ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -g -Os -pipe -Wall -Werror -Wno-string-plus-int -fPIE -D__FBSDID=__RCSID -DTERMCAP -DKLUDGELINEMODE -DUSE_TERMIO -DENV_HACK -DAUTHENTICATION -DKRB5 -DSKEY -DIPSEC -DINET6 -DFORWARD -I. -I../finkbuild/telnet/Build/telnet -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -c -o ../finkbuild/telnet/Build/telnet/commands.o commands.c 
commands.c:434:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C23
      [-Werror,-Wdeprecated-non-prototype]
  434 | send_dontcmd(name)
      | ^
1 error generated.
```

This is the file in question: https://github.com/apple-oss-distributions/remote_cmds/blob/remote_cmds-64/telnet.tproj/commands.c

as far as I can tell, it already has a prototype of `send_dontcmd()`:

```
static int
	send_esc(void),
	send_help(void),
	send_docmd(char *),
	send_dontcmd(char *),
	send_willcmd(char *),
	send_wontcmd(char *);
```
Am I missing something?

**Comment by dhomeier** [comment]
Notably the declaration
https://github.com/apple-oss-distributions/remote_cmds/blob/45181fc07b2887dd4f576abf80ad5063023b7f1d/telnet.tproj/commands.c#L433-L434

does not follow the style of all the other `send_*cmd`s; maybe patching this to `send_dontcmd(char *name)` will help?

**Comment by nieder** [comment]
@dhomeier thanks. that was the problem. See #1313.
