### ISSUE TITLE
Python27, Python37, Python38 builds fail on MacOS 10.14 / Xcode 11.3.1

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#655]
Am I using the wrong version of readline in Python37 and 38?  I have both readline6-shlibs and readlin7-shlibs installed.  readline6-shlibs is a required package for libxml2.

The other error in CMSDecoder.h I am stumped on.

After a self update, I tried a rebuild of Python 2.7 with the command "fink -ym rebuild python27 > ~/Desktop/fink-python27-log.txt 2>&1”.  I get the following error:

/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/CMSDecoder.h:130:5: error: expected function body after function declarator
1 warning and 1 error generated.
make: *** [sharedmods] Error 1

The Xcode and Dev Tools agree in version:
Package manager version: 0.45.1
Distribution version: selfupdate-git Tue Jul 28 08:37:08 2020, 10.14.5, x86_64
Trees: local/main stable/main
Xcode.app: 11.3.1
Xcode command-line tools: 11.3.1.0.1.1576735732
Max. Fink build jobs:  16

In python 3.7 and 3.8 I get the same error but all these additional errors:
/opt/sw/src/fink.build/python37-3.7.8-1/Python-3.7.8/Modules/readline.c:281:19: error: implicit declaration of function 'append_history' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
/opt/sw/src/fink.build/python37-3.7.8-1/Python-3.7.8/Modules/readline.c:1036:5: error: use of undeclared identifier 'rl_completion_suppress_append'
/opt/sw/src/fink.build/python37-3.7.8-1/Python-3.7.8/Modules/readline.c:1179:5: error: use of undeclared identifier 'rl_catch_signals'
/opt/sw/src/fink.build/python37-3.7.8-1/Python-3.7.8/Modules/readline.c:1202:17: error: implicit declaration of function 'rl_resize_terminal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
2 warnings and 4 errors generated.

Attached are the complete output logs.
[fink-python38-log.txt](https://github.com/fink/fink-distributions/files/4988563/fink-python38-log.txt)
[fink-python37-log.txt](https://github.com/fink/fink-distributions/files/4988564/fink-python37-log.txt)
[fink-python27-log.txt](https://github.com/fink/fink-distributions/files/4988565/fink-python27-log.txt)

-Scott

**Comment by nieder** [comment]
99% sure you have a mismatch of installed SDKs between Xcode and the command line tools.

As mentioned in [#624](https://github.com/fink/fink-distributions/issues/624#issuecomment-640119124) and the linked thread to the fink-users mailing list, what's the output of this command:
```
/bin/ls -Fl /Library/Developer/CommandLineTools/SDKs /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
```

You should see this:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs:
total 0
drwxr-xr-x  4 nieder  staff  128 Nov  7  2019 DriverKit19.0.sdk/
drwxr-xr-x  8 nieder  staff  256 Nov  7  2019 MacOSX.sdk/
lrwxr-xr-x  1 nieder  staff   10 Apr  6 05:59 MacOSX10.15.sdk@ -> MacOSX.sdk

/Library/Developer/CommandLineTools/SDKs:
total 0
lrwxr-xr-x  1 root  wheel   15 Apr  6 06:23 MacOSX.sdk@ -> MacOSX10.15.sdk
lrwxr-xr-x  1 root  wheel   10 Jul 23  2019 MacOSX10.14.sdk@ -> MacOSX.sdk
drwxr-xr-x  8 root  wheel  256 Apr  6 06:24 MacOSX10.15.sdk/
```

**Comment by sth0** [comment]
> On Jul 28, 2020, at 9:46 AM, nieder <notifications@github.com> wrote:
> 
> 
> 99% sure you have a mismatch of installed SDKs between Xcode and the command line tools.
> 
> As mentioned in #624 <https://github.com/fink/fink-distributions/issues/624#issuecomment-640119124> and the linked thread to the fink-users mailing list, what's the output of this command:
> 
> /bin/ls -Fl /Library/Developer/CommandLineTools/SDKs /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
> You should see this:
> 
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs:
> total 0
> drwxr-xr-x  4 nieder  staff  128 Nov  7  2019 DriverKit19.0.sdk/
> drwxr-xr-x  8 nieder  staff  256 Nov  7  2019 MacOSX.sdk/
> lrwxr-xr-x  1 nieder  staff   10 Apr  6 05:59 MacOSX10.15.sdk@ -> MacOSX.sdk
> 
> /Library/Developer/CommandLineTools/SDKs:
> total 0
> lrwxr-xr-x  1 root  wheel   15 Apr  6 06:23 MacOSX.sdk@ -> MacOSX10.15.sdk
> lrwxr-xr-x  1 root  wheel   10 Jul 23  2019 MacOSX10.14.sdk@ -> MacOSX.sdk
> drwxr-xr-x  8 root  wheel  256 Apr  6 06:24 MacOSX10.15.sdk/
And I see:
% /bin/ls -Fl /Library/Developer/CommandLineTools/SDKs /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs:
total 0
drwxr-xr-x  4 root  wheel  128 Jan  2  2020 DriverKit19.0.sdk/
drwxr-xr-x  8 root  wheel  256 Jan  2  2020 MacOSX.sdk/
lrwxr-xr-x  1 root  wheel   10 Jan  2  2020 MacOSX10.15.sdk@ -> MacOSX.sdk

/Library/Developer/CommandLineTools/SDKs:
total 0
lrwxr-xr-x  1 root  wheel   15 Jul  2 09:13 MacOSX.sdk@ -> MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 Jul  2 09:14 MacOSX10.14.sdk/
drwxr-xr-x  8 root  wheel  256 Jul  2 09:15 MacOSX10.15.sdk/
% 

Which seems to have a missing symbolic link in /Library/Developer/CommandLineTools/SDKs and an actual folder?   I will blow away the /Library/Developer and try to install a new Developer tool build.  Possibly in updating the developer tools without removing them beforehand leads to this issue?

-Scott

**Comment by sth0** [comment]
> On Jul 28, 2020, at 9:46 AM, nieder <notifications@github.com> wrote:
> 
> 
> 99% sure you have a mismatch of installed SDKs between Xcode and the command line tools.
> 
After removing the /Library/Developer/COmmandLine folder completely and reinstalling the Commandline tools 11.3.1 from a fresh copy downloaded from Apple. I have the same setup for those directories.

% /bin/ls -Fl /Library/Developer/CommandLineTools/SDKs /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs:
total 0
drwxr-xr-x  4 root  wheel  128 Jan  2  2020 DriverKit19.0.sdk/
drwxr-xr-x  8 root  wheel  256 Jan  2  2020 MacOSX.sdk/
lrwxr-xr-x  1 root  wheel   10 Jan  2  2020 MacOSX10.15.sdk@ -> MacOSX.sdk

/Library/Developer/CommandLineTools/SDKs:
total 0
lrwxr-xr-x  1 root  wheel   15 Jul 28 09:57 MacOSX.sdk@ -> MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 Aug 27  2019 MacOSX10.14.sdk/
drwxr-xr-x  8 root  wheel  256 Nov  7  2019 MacOSX10.15.sdk/
% 

The MacOSX10.14.sdk folder is an actual folder and not a link. This is running on MacOS 10.14.

-Scott

**Comment by nieder** [comment]
That's very strange that you have both SDKs as real directories. On all my systems, MacOSX10.14.sdk points to MacOSX.sdk, which points to real directory MacOSX10.15.sdk. You can always move the MacOSX10.14.sdk to MacOSX10.14.sdk.orig, then `ln -sf MacOSX10.14.sdk MacOSX.sdk`

**Comment by sth0** [comment]
Is the difference that you are on 10.15 and I am on 10.14?  Have you done a clean install of Xcode 11.3.1 Command Line Tools?

Should the python package explicitly look for the 10.15 SDK and only if it is not available use the generic MacOS SDK?  Asking folks to modify their Command Line Tools installation seems troubling.

I redid the link to match your system. Now Python 2.7, 3.7 and 3.8 all build as well as openblas.   So this helps but one has to modify the standard installation of Xcode command line tools.

-Scott

**Comment by nieder** [comment]
My output above is from 10.14/Xcode11.3. At this point, I don't know if the current install state of the CLT are from a clean install of the CLT (after deleting /Library/Developer/CommandLineTools) or by running the DMG installer (I've done both in the past).

Interestingly, on my 10.15/Xcode11.5 VM, for the CommandLineTools, I have real directories MacOSX10.14.sdk and MacOSX10.15.sdk, with the MacOSX.sdk symlink pointing to MacOSX10.15.sdk. For the Xcode.app SDKs, the real directory is MacOSX.sdk and MacOSX10.15.sdk is the symlink. And my python3X packages build fine (because the CLT and Xcode.app SDKs match).

You are right that users shouldn't have to modify system paths to get things working. So the question is figuring out why the installs are different, and if there's a way to work around that inside the Fink build process.

**Comment by nieder** [comment]
I just deleted my CLT on 10.14 and reinstalled from a fresh CLT v11.3.1 dmg installer. I got real directories for 10.14 and 10.15 SDKs and an unversioned symlink (thanks Apple for changing things!).

So I can get things to fail now. Yay ?

@danielj7 If I comment out the conditional CPPFLAGS that set -I$SDK_PATH/usr/include, python38 still works on 10.14/Xcode11.3.1 if I leave the adjacent SDK_PATH perl-pie to setup.py. I'm going through pythonXX iterations on 10.14 and 10.15 to see if I can build on all of them with just this minor change.
Now as to why it was needed before but might not be any more, I don't know.

**Comment by sth0** [comment]
Yay??  Indeed.  Sigh, this has been a big ball of mud type operation to get Python versions to compile on various OS / CLT /Xcode versions.   I have my home machine on 10.11 and CLT/Xcode version 8.2.1 as some extreme variations?

**Comment by nieder** [comment]
Summary on 10.14.6/Xcode11.3.1 (both CLT SDKs are real directories and MacOSK.sdk is a symlink to MacOSX10.15.sdk. $SDK_PATH points to the Xcode.app symlink MacOSX10.15.sdk (no Xcode.app MacOSX10.14.sdk)):
* python27: fails (_scproxy module failure) when adding $SDK_PATH/usr/include to CPPFLAGS. Succeeds if SDK_PATH not added.
* python34: fails (readline and _scproxy module failure) when adding $SDK_PATH/usr/include to CPPFLAGS. Succeeds if SDK_PATH not added.
* python35: compiler errors building readline and _scproxy modules, but build still somehow finishes with $SDK_PATH/usr/include present. No errors w/out $SDK_PATH/usr/include.
* python36: same as python35.
* python37: fails (readline, _sqlite, and _scproxy module failure) when adding $SDK_PATH/usr/include to CPPFLAGS. Succeeds if SDK_PATH not added.
* python38: fails (_scproxy module failure) when adding $SDK_PATH/usr/include to CPPFLAGS. Succeeds if SDK_PATH not added.

I did not touch the $SDK_PATH perl-pie to setup.py.

---

On 10.14.4 with Xcode10.2 (CLT and Xcode.app have only real MacOSX.sdk and MacOSX10.14.sdk symlink. /usr/include does not exist)
* All pythonXX packages build successfully w/ and w/out $SDK_PATH added to CPPFLAGS (perl-pie to setup.py still present).

**Comment by sth0** [comment]
Just because I have an older machine at home….
Mac OS 10.11.6 / Xcode 8.2.1 /CLT 8.2.1

% /bin/ls -lF /Library/Developer/CommandLineTools/SDKs/
total 16
drwxr-xr-x  5 root  wheel  170 Sep 17  2017 MacOSX.sdk/
lrwxr-xr-x  1 root  wheel   10 Dec 13  2016 MacOSX10.12.sdk@ -> MacOSX.sdk

And here the MacOSX.sdk is a real directory and the versioned SDK links to the vanilla named one.

Python 2.7, 3.7 and 3.8 all build correctly.
-sth

**Comment by dhomeier** [comment]
There are apparently problems beyond that with 3.5 and 3.6, getting readline-related errors ike this
```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -Wno-nullability-completeness -Werror=declaration-after-statement -I./Include -I. -I/opt/include/ncursesw -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/opt/include -I/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Include -I/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9 -c /private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/_scproxy.c -o build/temp.macosx-10.14-x86_64-3.5/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/_scproxy.o
/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/readline.c:282:19: warning: implicit declaration of function 'append_history' is
      invalid in C99 [-Wimplicit-function-declaration]
    errno = err = append_history(nelements, filename);
                  ^
/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/readline.c:282:19: warning: this function declaration is not a prototype
      [-Wstrict-prototypes]
/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/readline.c:1039:5: error: use of undeclared identifier
      'rl_completion_suppress_append'
    rl_completion_suppress_append = 0;
    ^
/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/readline.c:1185:5: error: use of undeclared identifier 'rl_catch_signals'
    rl_catch_signals = 0;
    ^
/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/readline.c:1208:17: warning: implicit declaration of function 'rl_resize_terminal'
      is invalid in C99 [-Wimplicit-function-declaration]
                rl_resize_terminal();
                ^
/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/readline.c:1208:17: warning: this function declaration is not a prototype
      [-Wstrict-prototypes]
4 warnings and 2 errors generated.
In file included from /private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/_scproxy.c:6:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:126:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:35:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:98:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/CMSDecoder.h:130:5: error: expected
      function body after function declarator
    __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_5, __MAC_10_13, __IPHONE_NA, __IPHONE_NA,
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/Availability.h:291:57: note: expanded
      from macro '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
                                                        __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep##_MSG(_msg)
                                                        ^
<scratch space>:78:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_5_DEP__MAC_10_13_MSG
^
/private/var/tmp/fink.build/python35-3.5.9-1/Python-3.5.9/Modules/_scproxy.c:74:10: warning: comparison of address of
      'kSCPropNetProxiesExcludeSimpleHostnames' not equal to a null pointer is always true [-Wtautological-pointer-compare]
    if (&kSCPropNetProxiesExcludeSimpleHostnames != NULL) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCSchemaDefinitions.h:1989:49: note: 
      expanded from macro 'kSCPropNetProxiesExcludeSimpleHostnames'
#define kSCPropNetProxiesExcludeSimpleHostnames kSCPropNetProxiesExcludeSimpleHostnames
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

Python build finished successfully!
The necessary bits to build these optional modules were not found:
ossaudiodev           spwd                                     
To find the necessary bits, look in setup.py in detect_modules() for the module's name.
(Fink package build should have 2 missing)

The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
atexit                pwd                   time               

Failed to build these modules:
_scproxy              readline
```
So this does not cause the build or selftest to fail, as these are not required modules, but then building almost any module on that Python fails, as a lot of them actually do expect `_scproxy`.

**Comment by nieder** [comment]
I've always had _scproxy and readline build errors to be fatal (just tested OK on 10.14.6/xcode11.3.1). Weird that they're not for you. What's the layout of /Library/Developer/CommandLineTools/SDKs? Should be two versioned directories and 1 unversioned symlink to 10.15

**Comment by dhomeier** [comment]
Exactly
```
lrwxr-xr-x  1 root  wheel   15  2 Oct 18:48 MacOSX.sdk@ -> MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 27 Aug  2019 MacOSX10.14.sdk/
drwxr-xr-x  8 root  wheel  256  7 Nov  2019 MacOSX10.15.sdk/
```
However, `xcrun --sdk macosx --show-sdk-path` points to
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk @ -> MacOSX.sdk
```
but the headers in that include dir seem to be identical to the ones in `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`. Yet `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/` somehow ends up in the include path, which obviously conflicts with the MacOSX10.15 versions.
In fact only the first part of the self-tests were passing; I missed a later failure precisely on `_scproxy` as I had set `--tests=warn`.

Now if I set SDK_PATH instead just to `xcrun --show-sdk-path` (i.e. /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk), the build completes for all essential modules and tests return a single failure on `test.test_grp.GroupDatabaseTestCase`.
`cython-py35` build looks to proceed fine so far!

Can you check if that option will also work with 10.14/Xcode 10.2 or 10.15, or will the script need further conditionals for OSX and Xcode version?

**Comment by nieder** [comment]
Works with and without, but I seem to remember earlier that we needed the versioned SDK to avoid mixing Xcode.app/SDK10.15 vs CLT/SDK10.14 (but that's somehow happening to you). Does the patch from #646 help if you then apply `flag-sort -v -r` to python's build?

**Comment by dhomeier** [comment]
> apply `flag-sort -v -r` to python's build?
You mean as in
`export CPPFLAGS="$(flag-sort -r echo -I%p/include -I%p/include/ncursesw -I$SDK_PATH/usr/include)"`

or hacking the `configure` or Makefile commands somehow to call `flag-sort` (would not really know where to start with the latter)?
This does not change anything in the order (strangely when calling `flag-sort -r` as my regular user, it does move `-I$SDK_PATH/usr/include` to the front, but that still has no impact on the Python build.

Not that with my `xcode-select` system defaults
```
xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
```
which is a symlink to `MacOSX.sdk` in a directory that has no 10.14 versions whatsoever; in contrast to the plain
```
xcrun --show-sdk-path
Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
```
But with those settings I also found issues with
```
> xcrun --show-sdk-version                                                                                                                                              
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk'
> xcrun --show-sdk-build-version                                                                                                                                        
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk" cannot be located.
xcrun: error: unable to lookup item 'ProductBuildVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk'
```
After `sudo xcode-select -switch /Library/Developer/CommandLineTools` things look a bit more sensible:
```
> xcrun --show-sdk-version                                                                                                                                              
10.14.5
> xcrun --show-sdk-build-version                                                                                                                                        
18F132
> xcrun --show-sdk-path                                                                                                                                                 
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
> xcrun --sdk macosx --show-sdk-version                                                                                                                                 
10.15.1
> xcrun --sdk macosx --show-sdk-build-version                                                                                                                           
19B90
> xcrun --sdk macosx --show-sdk-path                                                                                                                                    
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```
but since the latter is the symlink `MacOSX10.15.sdk` the include problems remain just the same when setting `SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"`.
I also tried the python35 build with setting
`CPPFLAGS='-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I%p/include -I%p/include/ncursesw -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include'`
– either explicitly or using `flag-sort`, which interestingly does put `MacOSX10.14.sdk` in front even as `fink-bld`, but the `readline` and `_scproxy` builds inevitably fail whenever `MacOSX10.15.sdk`is in the include path with errors like
```
building 'readline' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -Wno-nullability-completeness -Wno-expansion-to-defined -Werror=declaration-after-statement -I./Include -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/opt/include/ncursesw -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/include -I/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Include -I/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10 -c /private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.c -o build/temp.macosx-10.14-x86_64-3.5/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.o
building '_scproxy' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -Wno-nullability-completeness -Wno-expansion-to-defined -Werror=declaration-after-statement -I./Include -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/opt/include/ncursesw -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/include -I/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Include -I/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10 -c /private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/_scproxy.c -o build/temp.macosx-10.14-x86_64-3.5/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/_scproxy.o
/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.c:282:19: warning: implicit declaration of function 'append_history' is
      invalid in C99 [-Wimplicit-function-declaration]
    errno = err = append_history(nelements, filename);
                  ^
/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.c:282:19: warning: this function declaration is not a prototype
      [-Wstrict-prototypes]
/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.c:1039:5: error: use of undeclared identifier
      'rl_completion_suppress_append'
    rl_completion_suppress_append = 0;
    ^
/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.c:1185:5: error: use of undeclared identifier 'rl_catch_signals'
    rl_catch_signals = 0;
    ^
/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.c:1208:17: warning: implicit declaration of function 'rl_resize_terminal'
      is invalid in C99 [-Wimplicit-function-declaration]
                rl_resize_terminal();
                ^
/private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/readline.c:1208:17: warning: this function declaration is not a prototype
      [-Wstrict-prototypes]
4 warnings and 2 errors generated.
In file included from /private/var/tmp/fink.build/python35-3.5.10-1/Python-3.5.10/Modules/_scproxy.c:6:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:126:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:35:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:98:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/CMSDecoder.h:130:5: error: expected
      function body after function declarator
    __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_5, __MAC_10_13, __IPHONE_NA, __IPHONE_NA,
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/Availability.h:291:57: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
                                                        __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep##_MSG(_msg)
                                                        ^
<scratch space>:78:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_5_DEP__MAC_10_13_MSG
```
so it does not look like any reshuffling of the paths could fix this.
If the plain `xcrun --show-sdk-path` really does not work on 10.15 they only way around this might be an extra option for `"$(uname -r | cut -d. -f1)" -eq 18` – unless my command line tools installation is somehow broken, but it was a fresh Xcode 11.3.1 installation on Mojave, and I could not find any way to force-reinstall with `xcode-select`.
